apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
   name: {{ include "myapp.fullname" . }}
   namespace: {{ .Values.namespace }}
   annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
   ingressClassName: nginx
   rules:
     - host: "{{ .Values.ingress.hostname }}"
       http:
          paths:
            - path: {{ .Values.ingress.workpath }}
              pathType: Prefix
              backend:
                 service:
                    name: {{ include "myapp.fullname" . }}-service
                    port:
                       number: {{ .Values.service.appPort }}